version: '3.7'
services:
  nodejs:
    container_name: cfms-frontend
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    volumes:
      - ".:/cfms-frontend"
    ports:
      - "8001:8080"
