version: '3.7'
services:
  nginx:
    container_name: cfms-nginx
    image: cfms-nginx
    init: true
    build:
      context: .
      dockerfile: docker/local/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - ".:/cfms"
    environment:
      - XDG_CONFIG_HOME=/cfms/storage/logs/
  php:
    container_name: cfms-php
    image: cfms-php
    init: true
    build:
      context: .
      dockerfile: docker/local/php/Dockerfile
      args:
        PHP_MODE: production
    depends_on:
      - mysql
    volumes:
      - ".:/cfms"
  mysql:
    container_name: cfms-mysql
    image: mysql:5.7.41
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - cfms-mysql-data:/var/lib/mysql
volumes:
  cfms-mysql-data:
    driver: local
